version: '3.1'

services:
  db:
    image: 'postgres:13.1-alpine'
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: motor
      POSTGRES_USER: motor
      POSTGRES_DB: motor

